project:
  type: book


book:
  title: "DevOps Carpentry"
  subtitle: "A Researcher's Guide to the Open Source Ecosystem"
  author: "Matthias Bannert"
  date: "7/12/2022"
  search: true
  sharing: [twitter]
  chapters:
    - index.qmd

format:
  html:
    theme: cosmo
