project:
  type: book


book:
  title: "Research Software Engineering"
  subtitle: "A Guide to the Open Source Ecosystem"
  author: "Matthias Bannert"
  cover-image: images/wizardry.jpg
  date: "9/23/2023"
  search: true
  sharing: [twitter]
  chapters:
    - index.qmd
execute: 
  freeze: true
format:
   html:
     theme: cosmo
  